### PR TITLE
Added some more metrics

### PR DESCRIPTION
**Pull request by geert-ijewski**
I had searched for a plugin like this but wasn't satisfied with the available metrics, so I added the ones which interested me. While at it I also changed some smaller things

### CODE REVIEW

**Comment by rossigee** [comment]
Looks good. Could you add a couple of lines to the 'readme.txt' to document the new metrics you've added?

Disclaimer: I don't use Woocommerce any more, so I can't test this. But more than happy to merge if it will be of benefit to others.

**Comment by geert-ijewski** [comment]
I have added the specific metrics. Would you also be willing to upload the new version to the wordpress plugin page?

**Comment by rossigee** [comment]
I was referring to the body of the readme that explains what metrics are gathered.

https://github.com/rossigee/woocommerce-prometheus-metrics/blob/0ec343f4cffbb0bb54707cb0aa9e47e82461d7c0/readme.txt#L14

It's missing the new metrics you've added. Once that's up-to-date, I'm happy to merge and push a new version to WP plugins repo. Thanks.

**Comment by geert-ijewski** [comment]
Oh alright I see. I have added them, thank you

**Pull request merged**
